version: '3'

services:
  backend: 
    build: .
    container_name: comic_mangahay_be
    env_file:
      - .docker.env
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis_cache_mangahay
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    container_name: postgres_mangahay
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=MANGAHAY
      - POSTGRES_USER=tvhao021102
      - POSTGRES_PASSWORD=raicy0222*
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  redis:
    driver: local
  docker-nest-postgres:
    driver: local
    