version: '3'

services:
  backend: 
    build: ./
    container_name: comic_mangahay_be
    env_file:
      - .production.env
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - mangahay_network
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - './redis:/data'
    networks:
      - mangahay_network

networks:
  mangahay_network:
    driver: bridge
    